dist: bionic
language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
before_deploy:
- mvn package
- mv application/target/application-1.0-SNAPSHOT.zip application/target/Kayak-1.0-SNAPSHOT.zip
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dbLgoGnapUVXv9XzCuq1mhcSUxpWLKL82WCitDRhI+XKlmdroMif1Zrg7kGAsPKJ8LZtN1yjuZVp8lZizFDa6gTsQEaql15t8TlYGYQ6lkzUKvsKSBSydSjVa+H1fbgso+5s400k9mZWd3U2PFx/R0gtoRjtJ8nw9E3cj2+M9enwblAwlssx1AebkMNnbPNiS/rueQa2FKazpOGFp89pjbJLeevW8nFh99DvMfm74uguNp+oljpFTpK6cEdlT+lcs9Sw4sp1ElO5IU1phUOoOveljBRdfRRqrn3FIn/N0MZxEfPiB/yIQKEBU8ah2ZqtYpv1ZPj1LH1n/2Zerz6e4B2mASeTaijO146Jk6+78DospU8rMoWN5uzTw2rvZ7DaOdza2jH2IR9I9cV3/vl1rAg+Z+kP+x2lGCF0ZItvjiYUYfU0azz2bucbVKLZojioLorPAMwzCdQ+WMG3CMz+BhFfjNhD4pt4FqCWNj0UgGmzl1mfb5caUzFg0RP+6CjuaLFIEceRNo0MtT/I/xWuJKywZUc9um6/iCRFQYkRsGOHJGg3oPQwOEgbdtTiK4I5JUlWpbjlQRfz0JUGlRrObpnHUp/3d/5w7vOlLl14ZYsiLYGi2Nw0IB2wsBwXb1rNu3a/mxZxWLTiPYaaxzXaOh9bDAtfytfSxZAeqA3S45c=
  file: application/target/Kayak-1.0-SNAPSHOT.zip
  on:
    repo: dschanoeh/Kayak
